# Generated by Django 2.2.4 on 2019-08-27 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platinumPiece', models.FloatField(default=0)),
                ('goldPiece', models.FloatField(default=0)),
                ('silverPiece', models.FloatField(default=0)),
                ('copperPiece', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulk', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SM', 'Simple Melee'), ('MM', 'Martial Melee'), ('SR', 'Simple Ranged'), ('MR', 'Martial Ranged')], max_length=100)),
                ('damage', models.CharField(max_length=100)),
                ('hands', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('AXE', 'Axe'), ('BOW', 'Bow'), ('BRAWLING', 'Brawling'), ('CLUB', 'Club'), ('DART', 'Dart'), ('FLAIL', 'Flail'), ('HAMMER', 'Hammer'), ('KNIFE', 'Knife'), ('PICK', 'Pick'), ('POLEARM', 'Polearm'), ('SHIELD', 'Shield'), ('SLING', 'Sling'), ('SPEAR', 'Spear'), ('SWORD', 'Sword')], max_length=100)),
                ('common', models.BooleanField()),
                ('exotic', models.BooleanField()),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Price')),
                ('traits', models.ManyToManyField(to='core.WeaponTrait')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulk', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('GT', 'General Tools'), ('CT', 'Climbing Tools'), ('PT', 'Profession Tools'), ('S', 'Storage'), ('RW', 'Read & Writing'), ('A', 'Appearance'), ('AE', 'Ambush Equipment'), ('CE', 'Camping Equipment'), ('I', 'Illumination'), ('M', 'Miscellaneous')], max_length=100)),
                ('hands', models.CharField(max_length=100)),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulk', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy'), ('S', 'Shield')], max_length=100)),
                ('ac_bonus', models.IntegerField()),
                ('tac_bonus', models.IntegerField()),
                ('check_penalty', models.IntegerField()),
                ('speed_penalty', models.IntegerField()),
                ('trait', models.CharField(blank=True, choices=[('C', 'Clumsy'), ('F', 'Fragile'), ('N', 'Noisy')], max_length=100)),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
