# Generated by Django 2.2.4 on 2019-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190827_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='ac_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='check_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='speed_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='tac_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
