# Generated by Django 2.2.4 on 2019-08-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190827_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='common',
            new_name='uncommon',
        ),
    ]
