# Generated by Django 2.2.4 on 2019-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190827_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='reload',
            field=models.IntegerField(default=0),
        ),
    ]
