# Generated by Django 2.2.4 on 2019-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weapon_reload'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
