# Generated by Django 2.2.4 on 2019-08-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weapon_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulk', models.CharField(max_length=100)),
                ('unitiesInPackage', models.IntegerField(default=10)),
                ('ammoForWeapons', models.ManyToManyField(to='core.Weapon')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
