# Generated by Django 2.2.4 on 2019-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ammunition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='exotic',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('SM', 'Simple Melee'), ('MM', 'Martial Melee'), ('SR', 'Simple Ranged'), ('MR', 'Martial Ranged'), ('EM', 'Exotic Melee')], max_length=100),
        ),
    ]
